# Generated by Django 4.1.5 on 2023-03-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_classify',
            field=models.CharField(default='U', max_length=255),
        ),
    ]
