# Generated by Django 4.1.5 on 2023-04-15 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=255)),
                ('corp_country', models.CharField(max_length=255, null=True)),
                ('corp_market', models.CharField(max_length=255, null=True)),
                ('corp_isin', models.CharField(max_length=255, null=True)),
                ('stock_code', models.CharField(max_length=255, null=True)),
                ('corp_sectors', models.CharField(max_length=255, null=True)),
                ('is_crawl', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('low_price_52', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('high_price_52', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('total_stock', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('market_capitalization', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('trade_quantity', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('trade_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('change_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('change_rate', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('corp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_id', to='services.corpid')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inquiry_category', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorpSummaryFinancialStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_date', models.DateField()),
                ('year', models.CharField(max_length=4)),
                ('quarter', models.CharField(max_length=2)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('operating_margin', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('net_profit_margin', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('debt_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cost_of_sales_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_dividend', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('dividend_payout_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('dividend_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('per', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('pbr', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('psr', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('ev_ebitda', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('bps', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('dps', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_asset', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('borrow_debt', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('corp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_summary', to='services.corpid')),
            ],
        ),
        migrations.CreateModel(
            name='CorpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_homepage_url', models.URLField(null=True)),
                ('corp_settlement_month', models.CharField(max_length=255, null=True)),
                ('corp_ceo_name', models.CharField(max_length=255, null=True)),
                ('corp_summary', models.TextField(null=True)),
                ('corp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corp_info', to='services.corpid')),
            ],
        ),
        migrations.AddConstraint(
            model_name='corpid',
            constraint=models.UniqueConstraint(fields=('corp_name', 'corp_isin', 'stock_code'), name='unique corp'),
        ),
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('corp_id', 'trade_date'), name='unique trade_date'),
        ),
        migrations.AddConstraint(
            model_name='corpsummaryfinancialstatements',
            constraint=models.UniqueConstraint(fields=('corp_id', 'year', 'quarter'), name='unique summaryfs'),
        ),
    ]
