# Generated by Django 4.1.5 on 2023-05-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('quarter', models.CharField(max_length=2)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cost_of_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('inventories', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_asset', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('current_asset', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('current_liability', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cash_and_cash_equivalents', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('corporate_tax', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('depreciation_cost', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cash_flows_from_operating', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cash_flows_from_investing_activities', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_dividend', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cost_of_sales_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('operating_margin', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('net_profit_margin', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('roa', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('debt_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('per', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('pbr', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('psr', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('bps', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('dps', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('ev_ebitda', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('ev_ocf', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('dividend_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('payout_ratio', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('corp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_index', to='services.corpid')),
            ],
        ),
    ]
