# Generated by Django 4.1.5 on 2023-03-13 02:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_inquiry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='tinymce'),
        ),
    ]
