# Generated by Django 4.1.5 on 2023-05-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_investmentindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentindex',
            name='cash_and_cash_equivalents',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='cash_flows_from_investing_activities',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='cash_flows_from_operating',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='corporate_tax',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='current_asset',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='current_liability',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='depreciation_cost',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='interest_expense',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='inventories',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='total_asset',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='total_capital',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='total_debt',
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='total_dividend',
        ),
    ]
