# Generated by Django 4.1.5 on 2023-03-15 05:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_inquiry_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=255)),
                ('corp_country', models.CharField(max_length=255)),
                ('corp_market', models.CharField(max_length=255)),
                ('corp_isin', models.CharField(max_length=255)),
                ('stock_code', models.CharField(max_length=255)),
                ('corp_sectors', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='CorpSummaryFinancialStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_date', models.DateField()),
                ('year', models.DateField()),
                ('month', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=19)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('operating_margin', models.DecimalField(decimal_places=2, max_digits=19)),
                ('net_profit_margin', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dept_ratio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cost_of_sales_ratio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_dividend', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dividend_payout_ratio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dividend_ratio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('per', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pbr', models.DecimalField(decimal_places=2, max_digits=19)),
                ('psr', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ev_ebitda', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ev_per_ebitda', models.DecimalField(decimal_places=2, max_digits=19)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bps', models.DecimalField(decimal_places=2, max_digits=19)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dps', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_dept', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_asset', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=19)),
                ('borrow_debt', models.DecimalField(decimal_places=2, max_digits=19)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('corp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_summary', to='services.corpid')),
            ],
        ),
        migrations.CreateModel(
            name='CorpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_homepage_url', models.URLField()),
                ('corp_settlement_date', models.DateField()),
                ('corp_ceo_name', models.CharField(max_length=255)),
                ('corp_summary', models.TextField()),
                ('corp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corp_info', to='services.corpid')),
            ],
        ),
    ]
