# Generated by Django 4.1.5 on 2023-05-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_investmentindex_cash_and_cash_equivalents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentindex',
            name='fs_type',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
