# Generated by Django 4.1.5 on 2023-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_investmentindex_fs_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentindex',
            old_name='payout_ratio',
            new_name='divdend',
        ),
        migrations.AddField(
            model_name='investmentindex',
            name='dividend_payout_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
