# Generated by Django 4.1.5 on 2023-03-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_corpid_alter_inquiry_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
