# Generated by Django 4.1.5 on 2023-05-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_payout_ratio_investmentindex_divdend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentindex',
            old_name='divdend',
            new_name='dividend',
        ),
    ]
