# Generated by Django 4.1.5 on 2023-03-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_corpsummaryfinancialstatements_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpid',
            name='corp_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpid',
            name='corp_isin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpid',
            name='corp_market',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpid',
            name='corp_sectors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpid',
            name='stock_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpinfo',
            name='corp_ceo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpinfo',
            name='corp_homepage_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='corpinfo',
            name='corp_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='borrow_debt',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='bps',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='cost_of_sales_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='dept_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='dividend',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='dividend_payout_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='dividend_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='dividend_yield',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='dps',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='eps',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='ev_ebitda',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='ev_per_ebitda',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='face_value',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='net_profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='operating_margin',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='operating_profit',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='pbr',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='per',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='psr',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='quick_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='roe',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='total_asset',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='total_capital',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='total_dept',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='corpsummaryfinancialstatements',
            name='total_dividend',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
