# Generated by Django 4.1.5 on 2023-03-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_corpid_corp_country_alter_corpid_corp_isin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpsummaryfinancialstatements',
            old_name='dept_ratio',
            new_name='debt_ratio',
        ),
    ]
