# Generated by Django 4.1.5 on 2023-05-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_corpsummaryfinancialstatements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpid',
            name='is_crawl',
        ),
        migrations.AddField(
            model_name='corpid',
            name='base_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
