# Generated by Django 4.1.5 on 2023-06-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_corpid_base_date_alter_stockprice_trade_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='high_price_52',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='low_price_52',
        ),
    ]
