# Generated by Django 4.1.5 on 2023-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_stockprice_high_price_52_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentindex',
            name='cost_of_sales',
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='bps',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='cost_of_sales_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='current_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='debt_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='dividend',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='dividend_payout_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='dividend_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='dps',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='eps',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='ev_ebitda',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='ev_ocf',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='net_profit',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='net_profit_margin',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='operating_margin',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='operating_profit',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='pbr',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='per',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='psr',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='quick_ratio',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='revenue',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='roa',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentindex',
            name='roe',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='change_price',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='change_rate',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='close_price',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='high_price',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='low_price',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='market_capitalization',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='open_price',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='total_stock',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='trade_price',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='trade_quantity',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
    ]
