# Generated by Django 4.1.5 on 2023-06-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_investmentindex_cost_of_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpinfo',
            name='corp_homepage_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
