# Generated by Django 4.1.5 on 2023-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_investmentindex_accounts_payable_turnover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentindex',
            old_name='total_assests_turnover',
            new_name='total_assets_turnover',
        ),
    ]
