# Generated by Django 4.1.5 on 2023-07-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_rename_total_assests_turnover_investmentindex_total_assets_turnover'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investmentindex',
            unique_together={('id', 'corp_id')},
        ),
    ]
