# Generated by Django 4.1.5 on 2023-07-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_investmentindex_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investmentindex',
            unique_together={('id', 'corp_id', 'year', 'quarter', 'fs_type')},
        ),
    ]
