# Generated by Django 4.1.5 on 2023-08-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_delete_inquiryanswer'),
        ('services', '0016_alter_investmentindex_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReitsInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_date', models.DateField()),
                ('listing_date', models.DateField()),
                ('settlement_cycle', models.CharField(max_length=255)),
                ('investment_assets_info', models.JSONField(default={})),
                ('borrowed_info', models.JSONField(default={})),
                ('update_date', models.DateField(auto_now=True)),
                ('corp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reits_inquiry', to='services.corpid')),
            ],
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
