# Generated by Django 4.1.5 on 2023-10-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_reitsinquiry_lastest_dividend_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpid',
            name='corp_sectors_main',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
