# Generated by Django 4.1.5 on 2023-10-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_corpid_corp_sectors_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpid',
            name='is_financial_industry',
            field=models.BooleanField(default=False),
        ),
    ]
