# Generated by Django 4.1.5 on 2023-04-15 01:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCollectDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_corp_collect_date', models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0))),
                ('last_stock_collect_date', models.DateField(default=datetime.date(2023, 4, 15))),
                ('last_summaryfs_collect_date', models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='InquiryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='services.inquiry')),
            ],
        ),
    ]
