# Generated by Django 4.1.5 on 2023-04-18 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastcollectdate',
            name='last_stock_collect_date',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
    ]
