# Generated by Django 4.1.5 on 2023-03-15 05:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_inquiryanswer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryanswer',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
