# Generated by Django 4.1.5 on 2023-05-12 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_lastcollectdate_last_stock_collect_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastcollectdate',
            name='last_stock_collect_date',
            field=models.DateField(default=datetime.date(2023, 5, 12)),
        ),
    ]
