# Generated by Django 4.1.5 on 2023-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_lastcollectdate_last_stock_collect_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastcollectdate',
            name='last_corp_collect_date',
        ),
        migrations.RemoveField(
            model_name='lastcollectdate',
            name='last_stock_collect_date',
        ),
        migrations.RemoveField(
            model_name='lastcollectdate',
            name='last_summaryfs_collect_date',
        ),
        migrations.AddField(
            model_name='lastcollectdate',
            name='collect_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lastcollectdate',
            name='collect_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastcollectdate',
            name='collect_user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
