# Generated by Django 4.1.5 on 2023-08-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_remove_lastcollectdate_last_corp_collect_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InquiryAnswer',
        ),
    ]
