"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
"""
@modified at 2023.03.02
@author OKS in Aimdat Team

@modified at 2023.05.25
@author JSU in Aimdat Team
"""
import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^vysx0t93kypry2yyuq3a@sm-9*wm(#x+n$vnf!%n3ncfmgdle'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

secret_file = os.path.join(BASE_DIR, 'secrets.json')

with open(secret_file) as f:
    secrets = json.loads(f.read())

def get_secret(setting, secrets=secrets):
    try:
        return secrets[setting]
    except:
        return 0

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_bleach',
    'tinymce',
    'axes',
    'admin_dashboard',
    'account',
    'services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'test_db.postgresql',
        'USER': 'root',
        'PASSWORD': 'aimdat1!',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#AUTHENTICATION_BACKEND Setting
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'account.backends.EmailBackend'
]

#Social Login Setting
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'INIT_PARAMS': {'cookie_policy': 'single_host_origin'},
        'FIELDS': ['email'],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
    },
    'naver': {
        'SCOPE': ['email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'INIT_PARAMS': {'cookie_policy': 'single_host_origin'},
        'FIELDS': ['email'],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,

    },
    'kakao': {
        'SCOPE': ['account_email'],
        'FIELDS': ['email'],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
    }
}

#User Model Setting
AUTH_USER_MODEL = 'account.User'

#AXES Setting
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.166667 #10분
AXES_LOCKOUT_TEMPLATE  = 'account/lockout.html' #로그인 실패 시 나오는 html 페이지

#Tinymce settings
TINYMCE_FILEBROWSER = False
TINYMCE_EXTRA_MEDIA = {
    "js": [
        "tinymce/tinymce.min.js", 
    ],
}
TINYMCE_DEFAULT_CONFIG = {
    'height' : 500,
    'cleanup_on_startup': True,
    'menubar': False,
    'toolbar': "styleselect | undo redo | bold italic | alignleft aligncenter alignright | help",
    'custom_undo_redo_levels': 10,
}

#Login Redirect URL
LOGIN_REDIRECT_URL = '/account/login/'

#Logout Redirect URL
LOGOUT_REDIRECT_URL = '/account/login/'